name: broken-link-checker
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  # schedule:
  #   - cron: "0 5 * * 5"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Broken Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue From File
        if: ${{ steps.lychee.outputs.exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
